name: "Event Preparation"

on:
  issues:
    types: [opened]

jobs:
  prepare-event:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: "Prepare Event and Update Dropdown"
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const script = fs.readFileSync('.github/workflows/event-prep.js', 'utf8');
            eval(script);
