
name: "Raffle Winner Selection"

on:
  workflow_dispatch:
    inputs:
      raffle_issue:
        description: "Select the raffle to pick winners for"
        required: true
        type: choice
        options:
          - "No raffles available yet"

jobs:
  pick-winners:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Pick and Announce Winners"
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const script = fs.readFileSync('.github/workflows/winner-selection.js', 'utf8');
            eval(script);
